# Dataset Preprocessing

In [7]:
import pandas as pd

In [8]:
iod_df = pd.read_csv("raw/indices_of_deprivation.csv")
population_df = pd.read_csv("raw/london_population.csv")

print(iod_df.head())
print(population_df.head())

  LSOA code (2011)     LSOA name (2011) Local Authority District code (2019)  \
0        E01000001  City of London 001A                            E09000001
1        E01000002  City of London 001B                            E09000001
2        E01000003  City of London 001C                            E09000001
3        E01000005  City of London 001E                            E09000001
4        E01032739  City of London 001F                            E09000001

  Local Authority District name (2019)  \
0                       City of London
1                       City of London
2                       City of London
3                       City of London
4                       City of London

   Index of Multiple Deprivation (IMD) Score  \
0                                        6.2
1                                        5.1
2                                       19.4
3                                       28.7
4                                       13.6

   Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)  \
0                                              29199
1                                              30379
2                                              14915
3                                               8678
4                                              20391

   Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)  \
0                                                  9
1                                                 10
2                                                  5
3                                                  3
4                                                  7

   Income Score (rate)  Income Rank (where 1 is most deprived)  \
0                  0.0                                   32831
1                  0.0                                   29901
2                  0.1                                   18510
3                  0.2                                    6029
4                  0.0                                   32638

   Income Decile (where 1 is most deprived 10% of LSOAs)  ...  \
0                                                 10      ...
1                                                 10      ...
2                                                  6      ...
3                                                  2      ...
4                                                 10      ...

   Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs)  \
0                                                 10
1                                                 10
2                                                  6
3                                                  6
4                                                  8

   Crime Score  Crime Rank (where 1 is most deprived)  \
0         -2.0                                  32662
1         -2.3                                  32789
2         -1.0                                  29363
3         -1.3                                  31059
4         -1.6                                  31947

   Crime Decile (where 1 is most deprived 10% of LSOAs)  \
0                                                 10
1                                                 10
2                                                  9
3                                                 10
4                                                 10

   Barriers to Housing and Services Score  \
0                                    29.5
1                                    24.4
2                                    40.1
3                                    39.9
4                                    46.3

   Barriers to Housing and Services Rank (where 1 is most deprived)  \
0                                               7319
1                                              11707
2                                               2157
3                                               2217
4                                                837

   Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs)  \
0                                                  3
1                                                  4
2                                                  1
3                                                  1
4                                                  1

   Living Environment Score  \
0                      31.9
1                      23.1
2                      40.5
3                      29.0
4                      49.2

   Living Environment Rank (where 1 is most deprived)  \
0                                               7789
1                                              13070
2                                               4092
3                                               9397
4                                               2040

   Living Environment Decile (where 1 is most deprived 10% of LSOAs)
0                                                  3
1                                                  4
2                                                  2
3                                                  3
4                                                  1

[5 rows x 28 columns]
      OA11CD   LSOA11CD All Ages  0  1  2  3  4  5   6  ...  81  82  83  84  \
0  E00000001  E01000001      250  0  0  2  0  4  7  10  ...   0   3   4   2
1  E00000003  E01000001      323  0  2  3  0  2  5   5  ...   2   0   0   0
2  E00000005  E01000001      143  0  0  2  2  2  0   3  ...   1   0   0   0
3  E00000007  E01000001      169  3  1  2  4  2  0   2  ...   0   0   0   0
4  E00166756  E01000001      240  4  1  1  3  4  0   3  ...   2   1   0   0

   85  86  87  88  89  90+
0   0   0   1   0   0    7
1   2   0   0   0   0   11
2   0   0   0   1   0    4
3   0   0   0   0   0    0
4   3   1   2   0   1    0

[5 rows x 94 columns]

In [9]:
print("iod_df columns:", iod_df.columns)
print("population_df columns:", population_df.columns)

iod_df columns: Index(['LSOA code (2011)', 'LSOA name (2011)',
       'Local Authority District code (2019)',
       'Local Authority District name (2019)',
       'Index of Multiple Deprivation (IMD) Score',
       'Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)',
       'Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)',
       'Income Score (rate)', 'Income Rank (where 1 is most deprived)',
       'Income Decile (where 1 is most deprived 10% of LSOAs)',
       'Employment Score (rate)', 'Employment Rank (where 1 is most deprived)',
       'Employment Decile (where 1 is most deprived 10% of LSOAs)',
       'Education, Skills and Training Score',
       'Education, Skills and Training Rank (where 1 is most deprived)',
       'Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)',
       'Health Deprivation and Disability Score',
       'Health Deprivation and Disability Rank (where 1 is most deprived)',
       'Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs)',
       'Crime Score', 'Crime Rank (where 1 is most deprived)',
       'Crime Decile (where 1 is most deprived 10% of LSOAs)',
       'Barriers to Housing and Services Score',
       'Barriers to Housing and Services Rank (where 1 is most deprived)',
       'Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs)',
       'Living Environment Score',
       'Living Environment Rank (where 1 is most deprived)',
       'Living Environment Decile (where 1 is most deprived 10% of LSOAs)'],
      dtype='object')
population_df columns: Index(['OA11CD', 'LSOA11CD', 'All Ages', '0', '1', '2', '3', '4', '5', '6',
       '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18',
       '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
       '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42',
       '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54',
       '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66',
       '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78',
       '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89',
       '90+'],
      dtype='object')

In [10]:
iod_df.rename(columns={"LSOA code (2011)": "LSOA11CD"}, inplace=True)
merged_df = iod_df.merge(population_df, on="LSOA11CD", how="inner")

In [11]:
merged_df = merged_df[['LSOA11CD', 'All Ages', 'Index of Multiple Deprivation (IMD) Score',]]

merged_df['All Ages'] = pd.to_numeric(merged_df['All Ages'], errors='coerce')

merged_df = merged_df.groupby('LSOA11CD', as_index=False).agg({
    'All Ages': 'sum',
    'Index of Multiple Deprivation (IMD) Score': 'first'  # Assuming IMD score remains the same for each LSOA11CD
})

merged_df = merged_df.rename(columns={
    'All Ages': 'population',
    'Index of Multiple Deprivation (IMD) Score': 'IMD score'
})

merged_df

       LSOA11CD  population  IMD score
0     E01000001      1749.0        6.2
1     E01000002      1678.0        5.1
2     E01000003      1900.0       19.4
3     E01000005      2181.0       28.7
4     E01000006      2117.0       19.8
...         ...         ...        ...
4830  E01033742      1705.0       13.1
4831  E01033743      2330.0       21.0
4832  E01033744      1810.0       29.4
4833  E01033745      1987.0       22.1
4834  E01033746      1389.0       21.8

[4835 rows x 3 columns]

In [12]:
merged_df.to_csv("socioeconomic_data.csv", index=False)